export type Product = {
    id: string;
    name: string;
    brand: string;
    category: 'Perro adulto' | 'Cachorro' | 'Gato adulto' | 'Gatito' | 'Snacks';
    pet: 'perro' | 'gato';
    emoji: string;
    bgClass: string;
    price: number;
    rating: number;
    description: string;
    composition: string[];
    nutrition: { name: string; value: string }[];
    usage: string;
};

export const products: Product[] = [
    {
        id: '1',
        name: 'ProBalance Adulto Cordero',
        brand: 'NaturaPet',
        category: 'Perro adulto',
        pet: 'perro',
        emoji: '🐕',
        bgClass: 'bg-amber-100',
        price: 42.9,
        rating: 5,
        description:
            'Alimento completo y balanceado para perros adultos, formulado con cordero fresco y arroz integral para una digestión saludable.',
        composition: [
            'Cordero fresco (32%)',
            'Arroz integral (24%)',
            'Avena entera',
            'Pulpa de remolacha',
            'Aceite de salmón',
            'Vitaminas y minerales quelados',
        ],
        nutrition: [
            { name: 'Proteína bruta', value: '26%' },
            { name: 'Grasa bruta', value: '15%' },
            { name: 'Fibra bruta', value: '3.2%' },
            { name: 'Humedad', value: '9%' },
            { name: 'Omega-3', value: '0.6%' },
        ],
        usage: 'Perros 5-10kg: 110g/día • 10-20kg: 180g/día • 20-30kg: 260g/día. Dividir en dos tomas.',
    },
    {
        id: '2',
        name: 'PuppyStart Pollo y Avena',
        brand: 'NaturaPet',
        category: 'Cachorro',
        pet: 'perro',
        emoji: '🐶',
        bgClass: 'bg-orange-100',
        price: 38.5,
        rating: 4,
        description: 'Crecimiento sano para cachorros con pollo fresco, DHA y calcio para huesos fuertes.',
        composition: [
            'Pollo fresco (38%)',
            'Avena',
            'Arroz',
            'Huevo deshidratado',
            'Aceite de pescado',
            'Prebióticos FOS',
        ],
        nutrition: [
            { name: 'Proteína bruta', value: '30%' },
            { name: 'Grasa bruta', value: '18%' },
            { name: 'Calcio', value: '1.4%' },
            { name: 'Fósforo', value: '1.0%' },
            { name: 'DHA', value: '0.3%' },
        ],
        usage: 'Cachorros hasta 12 meses, 3 tomas al día según peso esperado adulto.',
    },
    {
        id: '3',
        name: 'FelineGourmet Salmón',
        brand: 'WhiskyCat',
        category: 'Gato adulto',
        pet: 'gato',
        emoji: '🐈',
        bgClass: 'bg-rose-100',
        price: 34.0,
        rating: 5,
        description: 'Receta premium con salmón salvaje, taurina y fibras para el control de bolas de pelo.',
        composition: [
            'Salmón fresco (40%)',
            'Arroz',
            'Guisantes',
            'Pulpa de manzana',
            'Taurina',
            'Levadura de cerveza',
        ],
        nutrition: [
            { name: 'Proteína bruta', value: '34%' },
            { name: 'Grasa bruta', value: '16%' },
            { name: 'Taurina', value: '0.2%' },
            { name: 'Fibra bruta', value: '4%' },
            { name: 'Humedad', value: '8%' },
        ],
        usage: 'Gatos 3-5kg: 50-70g/día. Mantener agua fresca disponible.',
    },
    {
        id: '4',
        name: 'KittenGrow Pollo Tierno',
        brand: 'WhiskyCat',
        category: 'Gatito',
        pet: 'gato',
        emoji: '🐱',
        bgClass: 'bg-pink-100',
        price: 29.9,
        rating: 4,
        description: 'Diseñado para gatitos en crecimiento, rico en proteína animal y DHA.',
        composition: ['Pollo (42%)', 'Hígado de pollo', 'Arroz', 'Huevo', 'Aceite de salmón', 'Calcio'],
        nutrition: [
            { name: 'Proteína bruta', value: '36%' },
            { name: 'Grasa bruta', value: '20%' },
            { name: 'Calcio', value: '1.3%' },
            { name: 'DHA', value: '0.25%' },
            { name: 'Humedad', value: '8%' },
        ],
        usage: 'Gatitos hasta 12 meses, libre acceso al alimento.',
    },
    {
        id: '5',
        name: 'Snacks Dentales Mini',
        brand: 'ChewJoy',
        category: 'Snacks',
        pet: 'perro',
        emoji: '🦴',
        bgClass: 'bg-yellow-100',
        price: 9.5,
        rating: 4,
        description: 'Premios dentales que ayudan a reducir el sarro mientras tu perro disfruta.',
        composition: ['Cereales', 'Carnes y derivados (12%)', 'Minerales', 'Clorofila', 'Menta'],
        nutrition: [
            { name: 'Proteína bruta', value: '12%' },
            { name: 'Grasa bruta', value: '3%' },
            { name: 'Fibra bruta', value: '5%' },
            { name: 'Humedad', value: '10%' },
        ],
        usage: '1 snack al día como complemento a la dieta principal.',
    },
    {
        id: '6',
        name: 'ProBalance Senior Pavo',
        brand: 'NaturaPet',
        category: 'Perro adulto',
        pet: 'perro',
        emoji: '🐕‍🦺',
        bgClass: 'bg-stone-100',
        price: 44.0,
        rating: 5,
        description: 'Para perros mayores de 7 años, con glucosamina y condroitina para articulaciones.',
        composition: ['Pavo (30%)', 'Arroz integral', 'Cebada', 'Glucosamina', 'Condroitina', 'Aceite de linaza'],
        nutrition: [
            { name: 'Proteína bruta', value: '24%' },
            { name: 'Grasa bruta', value: '12%' },
            { name: 'Fibra bruta', value: '4%' },
            { name: 'Glucosamina', value: '600 mg/kg' },
            { name: 'Humedad', value: '9%' },
        ],
        usage: 'Perros senior, ajustar ración según peso y nivel de actividad.',
    },
    {
        id: '7',
        name: 'FelineLight Pollo',
        brand: 'WhiskyCat',
        category: 'Gato adulto',
        pet: 'gato',
        emoji: '🐅',
        bgClass: 'bg-fuchsia-100',
        price: 31.5,
        rating: 4,
        description: 'Receta ligera para gatos con tendencia al sobrepeso o esterilizados.',
        composition: ['Pollo (35%)', 'Maíz', 'Fibra de guisante', 'L-carnitina', 'Taurina'],
        nutrition: [
            { name: 'Proteína bruta', value: '32%' },
            { name: 'Grasa bruta', value: '10%' },
            { name: 'Fibra bruta', value: '6%' },
            { name: 'L-carnitina', value: '200 mg/kg' },
            { name: 'Humedad', value: '8%' },
        ],
        usage: 'Gatos esterilizados 4kg: 45g/día.',
    },
    {
        id: '8',
        name: 'Snacks Salmón para Gatos',
        brand: 'ChewJoy',
        category: 'Snacks',
        pet: 'gato',
        emoji: '🐟',
        bgClass: 'bg-sky-100',
        price: 6.9,
        rating: 5,
        description: 'Bocaditos crujientes con relleno cremoso de salmón, irresistibles.',
        composition: ['Cereales', 'Pescado y derivados (15%)', 'Aceites', 'Levadura'],
        nutrition: [
            { name: 'Proteína bruta', value: '30%' },
            { name: 'Grasa bruta', value: '16%' },
            { name: 'Fibra bruta', value: '2%' },
            { name: 'Humedad', value: '9%' },
        ],
        usage: 'Hasta 10 unidades al día.',
    },
    {
        id: '9',
        name: 'ProBalance Razas Grandes',
        brand: 'NaturaPet',
        category: 'Perro adulto',
        pet: 'perro',
        emoji: '🐺',
        bgClass: 'bg-lime-100',
        price: 49.9,
        rating: 5,
        description: 'Croqueta XL para razas grandes, con soporte articular y digestión cuidada.',
        composition: ['Pollo (32%)', 'Arroz', 'Cebada', 'Glucosamina', 'Aceite de salmón', 'Yucca schidigera'],
        nutrition: [
            { name: 'Proteína bruta', value: '26%' },
            { name: 'Grasa bruta', value: '14%' },
            { name: 'Fibra bruta', value: '3%' },
            { name: 'Calcio', value: '1.1%' },
            { name: 'Humedad', value: '9%' },
        ],
        usage: 'Perros >25kg, una a dos tomas diarias.',
    },
    {
        id: '10',
        name: 'PuppyStart Razas Mini',
        brand: 'NaturaPet',
        category: 'Cachorro',
        pet: 'perro',
        emoji: '🐩',
        bgClass: 'bg-emerald-100',
        price: 36.0,
        rating: 4,
        description: 'Cachorros de razas pequeñas: croqueta diminuta, alta densidad energética.',
        composition: ['Pollo (35%)', 'Arroz', 'Huevo', 'Aceite de pescado', 'Prebióticos'],
        nutrition: [
            { name: 'Proteína bruta', value: '32%' },
            { name: 'Grasa bruta', value: '20%' },
            { name: 'Calcio', value: '1.3%' },
            { name: 'DHA', value: '0.3%' },
            { name: 'Humedad', value: '8%' },
        ],
        usage: 'Cachorros mini hasta 10 meses.',
    },
    {
        id: '11',
        name: 'FelineIndoor Pollo & Arroz',
        brand: 'WhiskyCat',
        category: 'Gato adulto',
        pet: 'gato',
        emoji: '😺',
        bgClass: 'bg-violet-100',
        price: 33.5,
        rating: 4,
        description: 'Para gatos de interior, con control de bolas de pelo y olor de heces.',
        composition: ['Pollo (33%)', 'Arroz', 'Pulpa de remolacha', 'Yucca', 'Taurina'],
        nutrition: [
            { name: 'Proteína bruta', value: '33%' },
            { name: 'Grasa bruta', value: '13%' },
            { name: 'Fibra bruta', value: '5%' },
            { name: 'Taurina', value: '0.2%' },
            { name: 'Humedad', value: '8%' },
        ],
        usage: 'Gatos de interior, 50g/día por cada 4kg.',
    },
    {
        id: '12',
        name: 'Galletas BBQ para Perros',
        brand: 'ChewJoy',
        category: 'Snacks',
        pet: 'perro',
        emoji: '🍖',
        bgClass: 'bg-red-100',
        price: 7.5,
        rating: 5,
        description: 'Galletas crujientes con sabor a barbacoa, sin azúcares añadidos.',
        composition: ['Cereales', 'Carnes (14%)', 'Aceites', 'Especias naturales'],
        nutrition: [
            { name: 'Proteína bruta', value: '14%' },
            { name: 'Grasa bruta', value: '5%' },
            { name: 'Fibra bruta', value: '4%' },
            { name: 'Humedad', value: '10%' },
        ],
        usage: 'Como premio, máx. 3 al día.',
    },
];

export const getProductById = (id: string) => products.find((p) => p.id === id);
